開発中のものをまとめるPR
sakupuu/rails_sns pull request #1
Opened 2021-04-25 01:27 UTC by sakupuu

・ユーザーログイン機能

2021-04-25 01:31 UTC, kaoru-kk requested changes

2021-04-25 01:31 UTC, kaoru-kk commented on app/controllers/application_controller.rb
> +    end
private
と
def のインデントを揃える
（defの方をprivateに合わせる

2021-04-25 01:31 UTC, kaoru-kk commented on app/controllers/application_controller.rb
> +  # end
コメントアウト消しましょー

2021-04-27 15:32 UTC, yuki-snow1823 approved these changes
承認しました！
ただし勉強のため確認お願いします。

2021-04-27 15:32 UTC, yuki-snow1823 commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
このコントローラーってなんのコントローラーですか？

2021-04-27 15:32 UTC, yuki-snow1823 commented on app/views/devise/registrations/new.html.erb
> +  <div class="field">
👏

2021-04-27 15:32 UTC, yuki-snow1823 commented on app/views/pages/index.html.erb
> +<h1>ようこそ</h1>
pagesはusersの方が良かったかもですね？
「冗長」とか言ったりします。
私もやりがちですが、命名の指す範囲が広すぎる時に使われます。

例）今回はいろんなpageが想定される。誰の？何の？という気持ちになるという感じです。

2021-04-27 15:32 UTC, yuki-snow1823 commented on config/routes.rb
> +  root 'pages#index'
今後でいいですが、deviseの追加とpages関連の追加はプルリク分けた方が良かったと思います。

2021-04-28 05:05 UTC, sakupuu commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
レビューありがとうございます！
そうですよね。私も途中で分かりづらくなって、エディタ上で名前を変更していました笑
usersに変更してあります。
よろしくお願いします。

2021-04-28 05:12 UTC, sakupuu commented on config/routes.rb
> +  root 'pages#index'
すみません。。プルリク分けるように教えていただく前にもう諸々やってしまっていたので。。次からそうします。

2021-04-28 05:17 UTC, merged