レイアウト編集
sakupuu/rails_sns pull request #15
Opened 2021-05-05 12:36 UTC by sakupuu

・scssファイルやcssファイルを編集
・それぞれのツイートにnameも追加
・Log InをSign Inに修正

2021-05-06 22:04 UTC, yuki-snow1823 approved these changes

2021-05-06 22:04 UTC, yuki-snow1823 commented on app/assets/stylesheets/application.css
> +.main-nav li {
閉じカッコのインデントが若干ずれてるかもです！

2021-05-07 05:10 UTC, kaoru-kk commented on app/controllers/tweets_controller.rb
> +    # @comment = @tweet.comments.build
コメントアウトが・・残ってます・・・

2021-05-07 05:10 UTC, kaoru-kk requested changes
良さげです！１点だけ 🙏

2021-05-07 12:23 UTC, sakupuu commented on app/assets/stylesheets/application.css
> +.main-nav li {
あら！かしこまりです。直します。

2021-05-07 12:24 UTC, sakupuu commented on app/controllers/tweets_controller.rb
> +    # @comment = @tweet.comments.build
あれ・・？消したと思ってましたが。。。直します！

2021-05-10 13:55 UTC, merged