フォローフォロワー機能
sakupuu/rails_sns pull request #6
Opened 2021-04-26 04:02 UTC by sakupuu

・他のユーザーをフォローする機能と他のユーザーからフォローされる機能を追加

2021-04-30 23:20 UTC, yuki-snow1823 commented
⚠️ちょっとコミットの粒度が大きいので注意しましょう！

https://github.com/sakupuu/rails_sns/pull/6/commits/d2689cce20eea6d832a4040b54a098718bd0376f
この中でも、作業ごとにセーブする感じです！
ここら辺授業で扱いましょうか。

2021-04-30 23:20 UTC, yuki-snow1823 commented
コンフリクトの修正をお願いします。

2021-04-30 23:22 UTC, yuki-snow1823 requested changes

2021-04-30 23:22 UTC, yuki-snow1823 commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
このテーブルはどんな役割をしているでしょう？

2021-04-30 23:22 UTC, yuki-snow1823 commented on app/models/relationship.rb
> +  belongs_to :following, class_name: "User"
class_nameを書くとどんなことができるでしょう？

2021-04-30 23:22 UTC, yuki-snow1823 commented on config/routes.rb
> +    get :follows, on: :member
いいですね！ただ、onmemberの理由や意味もぜひ教えてください

2021-05-01 04:19 UTC, sakupuu commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
こちらは中間テーブルと呼ばれるものです！
各親テーブルのprimary_keyをforeign_keyとして保存できます。
 今回の場合だと、Relationshipを介してFollowerやFollowingを集めることができます。

2021-05-01 04:42 UTC, sakupuu commented on app/models/relationship.rb
> +  belongs_to :following, class_name: "User"
belongs_to は 1番目の引数を関連先のクラス名として扱うので、belongs_to :followingだけだと関連先のモデル(クラス)はFollowingに変換されてしまうので、class_name: "User"と付け加えることで、Userモデル(クラス) のオブジェクトを取得する事ができます！

2021-05-01 04:58 UTC, sakupuu commented on config/routes.rb
> +    get :follows, on: :member
意味：memberメソッドを使うとユーザーidが含まれているURLを扱えるようになる。
理由：memberルーティングが1つだけしかないので、:onオプションを指定することでブロックを省略できるから。

2021-05-04 01:33 UTC, yuki-snow1823 commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
おっけいです！

2021-05-04 01:34 UTC, yuki-snow1823 commented on config/routes.rb
> +    get :follows, on: :member
おっけいですー

2021-05-04 01:34 UTC, yuki-snow1823 approved these changes

2021-05-04 12:41 UTC, merged