ツイート内容を編集・削除
sakupuu/rails_sns pull request #7
Opened 2021-04-26 13:01 UTC by sakupuu

・ツイートした人がその内容を編集・削除する設定を追加

2021-05-05 21:37 UTC, yuki-snow1823 commented on app/controllers/tweets_controller.rb
> +    # @comment = @tweet.comments.build
削除しておきましょう。

2021-05-05 21:38 UTC, yuki-snow1823 commented on app/controllers/tweets_controller.rb
> +      render :new
これってnewするページと一覧ページは別なのでしたっけ？

2021-05-05 21:41 UTC, yuki-snow1823 reviewed
コメントしました！

2021-05-05 21:41 UTC, yuki-snow1823 commented
コンフリクトの解消もお願いします！

2021-05-06 00:53 UTC, sakupuu commented on app/controllers/tweets_controller.rb
> +    # @comment = @tweet.comments.build
かしこまりです！！完了しました！

2021-05-06 00:56 UTC, sakupuu commented on app/controllers/tweets_controller.rb
> +      render :new
いえ！同じです！
いらないですね。消します！

2021-05-06 21:48 UTC, yuki-snow1823 commented on app/controllers/comments_controller.rb
> +      render :new
newの削除ありがとうございました！
そうすると、このエラーが出た時のrender先ってnewで大丈夫そうですか？

2021-05-06 21:48 UTC, yuki-snow1823 reviewed
1件コメントしました！

2021-05-07 05:07 UTC, kaoru-kk requested changes
コメントしました！

2021-05-07 05:07 UTC, kaoru-kk commented on app/controllers/comments_controller.rb
> +    @tweet = Tweet.find(params[:tweet_id])
超細かくいうと、ここはインスタンス変数ではない方が良きです
viewに変数を渡す必要はないのでローカル変数にしましょー

@tweet = Tweet.find(params[:tweet_id])
ではなく
tweet = Tweet.find(params[:tweet_id])

2021-05-07 05:08 UTC, kaoru-kk commented on app/controllers/comments_controller.rb
> +  end
このメソッド使わなければ消しちゃいましょー！

2021-05-07 12:07 UTC, sakupuu commented on app/controllers/comments_controller.rb
> +      render :new
レビューありがとうございます。
else~から削除したので、データが更新されてもされなくても、一覧ページの方に飛びます。

2021-05-07 12:07 UTC, sakupuu commented on app/controllers/comments_controller.rb
> +    @tweet = Tweet.find(params[:tweet_id])
レビューありがとうございます。
そうなんですね。かしこまりです。直します。

2021-05-07 12:17 UTC, sakupuu commented on app/controllers/comments_controller.rb
> +  end
かしこまりです！

2021-05-08 00:05 UTC, yuki-snow1823 commented
@sakupuu 細かいですが 4d4982b のコミットにて、削除以外のこともしているのでコミット分けた方が良かったかもです！今度から気をつけていきましょう。

2021-05-08 00:05 UTC, yuki-snow1823 approved these changes

2021-05-09 04:53 UTC, kaoru-kk approved these changes
一件だけコメントしてます、LGTM!

2021-05-09 04:54 UTC, kaoru-kk commented on app/controllers/comments_controller.rb
> +    @comment = tweet.comments.find(params[:id])
ここもローカル変数でおけですよー

2021-05-09 12:24 UTC, sakupuu commented on app/controllers/comments_controller.rb
> +    @comment = tweet.comments.find(params[:id])
かしこまりです！！

2021-05-09 12:30 UTC, merged